server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para rotas da API Back-end
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        # Suporte a Server-Sent Events (SSE) sem buffering do Nginx
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
    }

    # Proxy para Dashboard Bull-Board
    location /admin/queues {
        proxy_pass http://backend:3000/admin/queues;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
